// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD41SmO_ipMHzq_zx2VeCVQ3qw0o10o0j4',
    appId: '1:276240811079:web:1b6ec830b7edf7df0cdd62',
    messagingSenderId: '276240811079',
    projectId: 'whiskai',
    authDomain: 'whiskai.firebaseapp.com',
    storageBucket: 'whiskai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBBL5m53H3x0ljZz2rXmy6Fv8JTgyhXr8',
    appId: '1:276240811079:android:e048052daf93371e0cdd62',
    messagingSenderId: '276240811079',
    projectId: 'whiskai',
    storageBucket: 'whiskai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANVImAUlfEP8zJ6J5hda8bhgvQwVpl4nY',
    appId: '1:276240811079:ios:6db2fa37493e599d0cdd62',
    messagingSenderId: '276240811079',
    projectId: 'whiskai',
    storageBucket: 'whiskai.appspot.com',
    iosClientId: '276240811079-3a2iod1hhf9j2vke28im57dkdo3s0r5g.apps.googleusercontent.com',
    iosBundleId: 'com.spacedsoft.whiskeyAi',
  );
}
